version: 2.1

commands:

  destroy-environment:
    description: "destroy environment "
    parameters:
      cf_stack:
        type: string
        default: "" 
    steps:
      - run:
          name: "Delete Cloudformation Stack"
          command:  aws cloudformation delete-stack --stack-name backend
          when: on_fail




jobs:
  build_backend:
    docker:
      - image: amazon/aws-cli
    steps:
    - checkout
    - run:
        name: cloudformation build via AWS CLI
        command: aws cloudformation deploy --stack-name backend --template-file .circleci/files/backend.yml

  build_frontend:
    docker:
      - image: amazon/aws-cli
    steps:
    - checkout
    - run:
        name: cloudformation build via AWS CLI
        command: aws cloudformation deploy --stack-name frontend --template-file .circleci/files/frontend.yml

  build_cloudfront:
    docker:
      - image: amazon/aws-cli
    steps:
    - checkout
    - run:
        name: cloudformation build via AWS CLI
        command: aws cloudformation deploy --stack-name cloudfront --template-file .circleci/files/cloudsfront.yml

workflows:
  execute_bulk:
    jobs:
      - build_backend
      - build_frontend
      - build_cloudfront
      - destroy-environment