version: 2.1



jobs:
  build_deploy:
    docker:
      - image: amazon/aws-cli
    steps:
    - checkout
    - run:
        name: cloudformation build via AWS CLI
        command: aws cloudformation create-stack --stack-name backend --template-body file://backend.yml 

workflows:
  execute_bulk:
    jobs:
      - build_deploy