version: 2.1



jobs:
  build_deploy:
    docker:
      - image: amazon/aws-cli
    steps:
    - checkout
    - run:
        name: cloudformation build via AWS CLI
        command: aws cloudformation create-stack --stack-name project2-2021-Network --template-body file://network.yml --parameters file://network-parameters.json

workflows:
  execute_bulk:
    jobs:
      - build_deploy