version: 2.1

# commands:

#   destroy_environment:
#     parameters:
#       when_to_run:
#         type: string
#         default: "on_fail"
#     steps:
#       - run:
#           name: Destroy Environments
#           command: |
#             aws delete-stack --stack-name backend
#           when: on_fail

  # destroy-environment:
  #   description: "destroy environment "
  #   parameters:
  #     cf_stack:
  #       type: string
  #       default: "" 
  #   steps:
  #     - run:
  #         name: "Delete Cloudformation Stack"
  #         command:  aws cloudformation delete-stack --stack-name backend
  #         when: on_fail




jobs:
  # build_backend:
  #   docker:
  #     - image: amazon/aws-cli
  #   steps:
  #   - checkout
  #   - run:
  #       name: cloudformation build via AWS CLI
  #       command: aws cloudformation deploy --stack-name backend --template-file .circleci/files/backend.yml


  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
            mkdir frontend
            cd frontend
            npm install
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          command: |
            mkdir backend
            cd backend
            npm install
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build

  funend:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: mkdir fronend && cd frontend && npm install





  # build_frontend:
  #   docker:
  #     - image: amazon/aws-cli
  #   steps:
  #   - checkout
  #   - run:
  #       name: cloudformation build via AWS CLI
  #       command: aws cloudformation deploy --stack-name frontend --template-file .circleci/files/frontend.yml

  # build_cloudfront:
  #   docker:
  #     - image: amazon/aws-cli
  #   steps:
  #   - checkout
  #   - run:
  #       name: cloudformation build via AWS CLI
  #       command: aws cloudformation deploy --stack-name cloudfront --template-file .circleci/files/cloudsfront.yml

workflows:
  execute_mark:
    jobs:
    - build-frontend
    - build-backend
    - funend
      # - build_backend
      # - buildnpm
      # - build_frontend
      # - build_cloudfront