version: 2.1

commands:

  destroy_environment:
    parameters:
      when_to_run:
        type: string
        default: "on_fail"
    steps:
      - run:
          name: Destroy Environments
          command: |
            aws delete-stack --stack-name backend
          when: on_fail

  # destroy-environment:
  #   description: "destroy environment "
  #   parameters:
  #     cf_stack:
  #       type: string
  #       default: "" 
  #   steps:
  #     - run:
  #         name: "Delete Cloudformation Stack"
  #         command:  aws cloudformation delete-stack --stack-name backend
  #         when: on_fail




jobs:
  build_backend:
    docker:
      - image: amazon/aws-cli
    steps:
    - checkout
    - run:
        name: cloudformation build via AWS CLI
        command: aws cloudformation deploy --stack-name backend --template-file .circleci/files/backend.yml


  buildnpm:
    docker:
      - image: circleci/node:10.15.3
    steps:
    - checkout
    - run:
          name: update-npm
          command: "sudo npm install -g npm@latest"
    - run:
          name: test
          command: npm test


  # build_frontend:
  #   docker:
  #     - image: amazon/aws-cli
  #   steps:
  #   - checkout
  #   - run:
  #       name: cloudformation build via AWS CLI
  #       command: aws cloudformation deploy --stack-name frontend --template-file .circleci/files/frontend.yml

  # build_cloudfront:
  #   docker:
  #     - image: amazon/aws-cli
  #   steps:
  #   - checkout
  #   - run:
  #       name: cloudformation build via AWS CLI
  #       command: aws cloudformation deploy --stack-name cloudfront --template-file .circleci/files/cloudsfront.yml

workflows:
  execute_bulk:
    jobs:
      - build_backend
      - buildnpm
      # - build_frontend
      # - build_cloudfront