version: 2.1

aws:
    docker:
      - image: amazon/aws-cli

jobs:
  build_deploy:
    executor: aws
    steps:
    - checkout
    - run:
        name: Installing AWS CLI
        command: sudo apt-get update | sudo apt install python3-pip | sudo pip3 install awsebcli --upgrade 

workflows:
  jobs:
    - build_deploy